import './style.css';
import { Viewport } from 'next';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: true,
  viewportFit: 'cover',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className="overflow-auto bg-[#1a1a2e] pt-[177.777778%]">{children}</body>
      </html>
    </>
  );
}
